In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [87]:
data_test = pd.read_csv(r'C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Test.csv')

In [88]:
data_test['Source'] = 'test'

In [89]:
data_test.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,test
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1,test
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store,test
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1,test
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3,test

In [90]:
data_test.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Source'],
      dtype='object')

In [91]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5681 entries, 0 to 5680
Data columns (total 12 columns):
Item_Identifier              5681 non-null object
Item_Weight                  4705 non-null float64
Item_Fat_Content             5681 non-null object
Item_Visibility              5681 non-null float64
Item_Type                    5681 non-null object
Item_MRP                     5681 non-null float64
Outlet_Identifier            5681 non-null object
Outlet_Establishment_Year    5681 non-null int64
Outlet_Size                  4075 non-null object
Outlet_Location_Type         5681 non-null object
Outlet_Type                  5681 non-null object
Source                       5681 non-null object
dtypes: float64(3), int64(1), object(8)
memory usage: 532.7+ KB

In [92]:
data_test.Item_Type.unique()

array(['Snack Foods', 'Dairy', 'Others', 'Fruits and Vegetables',
       'Baking Goods', 'Health and Hygiene', 'Breads', 'Hard Drinks',
       'Seafood', 'Soft Drinks', 'Household', 'Frozen Foods', 'Meat',
       'Canned', 'Starchy Foods', 'Breakfast'], dtype=object)

In [93]:
data_train = pd.read_csv(r'C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Train.csv')

In [94]:
data_train['Source'] = 'train'
data_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,train
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,train
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,train

In [95]:
total_data = pd.concat([data_test,data_train],sort=False)

In [96]:
total_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source,Item_Outlet_Sales
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,test,NaN
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1,test,NaN
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store,test,NaN
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1,test,NaN
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3,test,NaN

In [97]:
total_data.apply(lambda x: sum(x.isnull()))

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Source                          0
Item_Outlet_Sales            5681
dtype: int64

In [98]:
total_data.dtypes.index

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Source', 'Item_Outlet_Sales'],
      dtype='object')

In [99]:
total_data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Source', 'Item_Outlet_Sales'],
      dtype='object')

In [100]:
categorical_columns = [x for x in total_data.dtypes.index if total_data.dtypes[x]== 'object']
categorical_columns

['Item_Identifier',
 'Item_Fat_Content',
 'Item_Type',
 'Outlet_Identifier',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type',
 'Source']

In [101]:
new_data = total_data[categorical_columns]

In [102]:
new_data.head()

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source
0,FDW58,Low Fat,Snack Foods,OUT049,Medium,Tier 1,Supermarket Type1,test
1,FDW14,reg,Dairy,OUT017,NaN,Tier 2,Supermarket Type1,test
2,NCN55,Low Fat,Others,OUT010,NaN,Tier 3,Grocery Store,test
3,FDQ58,Low Fat,Snack Foods,OUT017,NaN,Tier 2,Supermarket Type1,test
4,FDY38,Regular,Dairy,OUT027,Medium,Tier 3,Supermarket Type3,test

In [103]:
new_data.drop(['Outlet_Identifier','Outlet_Identifier'],axis=True)

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source
0,FDW58,Low Fat,Snack Foods,Medium,Tier 1,Supermarket Type1,test
1,FDW14,reg,Dairy,NaN,Tier 2,Supermarket Type1,test
2,NCN55,Low Fat,Others,NaN,Tier 3,Grocery Store,test
3,FDQ58,Low Fat,Snack Foods,NaN,Tier 2,Supermarket Type1,test
4,FDY38,Regular,Dairy,Medium,Tier 3,Supermarket Type3,test
5,FDH56,Regular,Fruits and Vegetables,Small,Tier 1,Supermarket Type1,test
6,FDL48,Regular,Baking Goods,Medium,Tier 3,Supermarket Type2,test
7,FDC48,Low Fat,Baking Goods,Medium,Tier 3,Supermarket Type3,test
8,FDN33,Regular,Snack Foods,NaN,Tier 2,Supermarket Type1,test
9,FDA36,Low Fat,Baking Goods,NaN,Tier 2,Supermarket Type1,test
10,FDT44,Low Fat,Fruits and Vegetables,NaN,Tier 2,Supermarket Type1,test
11,FDQ56,Low Fat,Fruits and Vegetables,NaN,Tier 2,Supermarket Type1,test
12,NCC54,Low Fat,Health and Hygiene,Small,Tier 1,Grocery Store,test
13,FDU11,Low Fat,Breads,Medium,Tier 1,Supermarket Type1,test
14,DRL59,LF,Hard Drinks,High,Tier 3,Supermarket Type1,test
15,FDM24,Regular,Baking Goods,Medium,Tier 1,Supermarket Type1,test
16,FDI57,Low Fat,Seafood,NaN,Tier 2,Supermarket Type1,test
17,DRC12,Low Fat,Soft Drinks,Medium,Tier 3,Supermarket Type2,test
18,NCM42,Low Fat,Household,Medium,Tier 3,Supermarket Type3,test
19,FDA46,Low Fat,Snack Foods,NaN,Tier 3,Grocery Store,test
20,FDA31,Low Fat,Fruits and Vegetables,High,Tier 3,Supermarket Type1,test
21,NCJ31,Low Fat,Others,Small,Tier 2,Supermarket Type1,test
22,FDG52,LF,Frozen Foods,Small,Tier 1,Supermarket Type1,test
23,NCL19,Low Fat,Others,Small,Tier 1,Grocery Store,test
24,FDS10,Low Fat,Snack Foods,Small,Tier 2,Supermarket Type1,test
25,FDX22,Regular,Snack Foods,NaN,Tier 3,Grocery Store,test
26,NCF19,Low Fat,Household,Small,Tier 2,Supermarket Type1,test
27,NCE06,Low Fat,Household,Small,Tier 1,Supermarket Type1,test
28,DRC27,Low Fat,Dairy,Small,Tier 1,Supermarket Type1,test
29,FDE21,LF,Fruits and Vegetables,Small,Tier 2,Supermarket Type1,test
...,...,...,...,...,...,...,...
8493,FDP21,Regular,Snack Foods,NaN,Tier 2,Supermarket Type1,train
8494,NCI54,Low Fat,Household,NaN,Tier 2,Supermarket Type1,train
8495,FDE22,Low Fat,Snack Foods,Small,Tier 2,Supermarket Type1,train
8496,FDJ57,Regular,Seafood,NaN,Tier 2,Supermarket Type1,train
8497,FDT08,Low Fat,Fruits and Vegetables,Small,Tier 2,Supermarket Type1,train
8498,NCP54,Low Fat,Household,Medium,Tier 3,Supermarket Type2,train
8499,NCK53,Low Fat,Health and Hygiene,Small,Tier 2,Supermarket Type1,train
8500,NCQ42,Low Fat,Household,NaN,Tier 2,Supermarket Type1,train
8501,FDW21,Regular,Snack Foods,NaN,Tier 2,Supermarket Type1,train
8502,NCH43,Low Fat,Household,NaN,Tier 2,Supermarket Type1,train
8503,FDQ44,Low Fat,Fruits and Vegetables,Small,Tier 2,Supermarket Type1,train
8504,NCN18,Low Fat,Household,Medium,Tier 3,Supermarket Type3,train
8505,FDB46,Regular,Snack Foods,Medium,Tier 3,Supermarket Type2,train
8506,DRF37,Low Fat,Soft Drinks,Medium,Tier 3,Supermarket Type2,train
8507,FDN28,Regular,Frozen Foods,Small,Tier 2,Supermarket Type1,train
8508,FDW31,Regular,Fruits and Vegetables,NaN,Tier 2,Supermarket Type1,train
8509,FDG45,Low Fat,Fruits and Vegetables,NaN,Tier 3,Grocery Store,train
8510,FDN58,Regular,Snack Foods,Small,Tier 2,Supermarket Type1,train
8511,FDF05,Low Fat,Frozen Foods,Medium,Tier 3,Supermarket Type2,train
8512,FDR26,Low Fat,Dairy,High,Tier 3,Supermarket Type1,train
8513,FDH31,Regular,Meat,Small,Tier 2,Supermarket Type1,train
8514,FDA01,Regular,Canned,NaN,Tier 2,Supermarket Type1,train
8515,FDH24,Low Fat,Baking Goods,Medium,Tier 3,Supermarket Type2,train
8516,NCJ19,Low Fat,Others,Medium,Tier 3,Supermarket Type2,train
8517,FDF53,reg,Frozen Foods,Small,Tier 1,Supermarket Type1,train
8518,FDF22,Low Fat,Snack Foods,High,Tier 3,Supermarket Type1,train
8519,FDS36,Regular,Baking Goods,NaN,Tier 2,Supermarket Type1,train
8520,NCJ29,Low Fat,Health and Hygiene,Small,Tier 2,Supermarket Type1,train
8521,FDN46,Regular,Snack Foods,Medium,Tier 3,Supermarket Type2,train
8522,DRG01,Low Fat,Soft Drinks,Small,Tier 1,Supermarket Type1,train

In [104]:
new_data.drop('Item_Identifier',axis=True).head()

,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source
0,Low Fat,Snack Foods,OUT049,Medium,Tier 1,Supermarket Type1,test
1,reg,Dairy,OUT017,NaN,Tier 2,Supermarket Type1,test
2,Low Fat,Others,OUT010,NaN,Tier 3,Grocery Store,test
3,Low Fat,Snack Foods,OUT017,NaN,Tier 2,Supermarket Type1,test
4,Regular,Dairy,OUT027,Medium,Tier 3,Supermarket Type3,test

In [105]:
new_data.shape

(14204, 8)

In [106]:
"""for item in categorical_columns:
    print('\n Frequency of categories for variable is ')
    print(data[item].value_counts())"""

"for item in categorical_columns:\n    print('\n Frequency of categories for variable is ')\n    print(data[item].value_counts())"

In [107]:
new_data['Outlet_Years'] = 2013-total_data['Outlet_Establishment_Year']

C:\Users\heman\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [108]:
new_data.head()

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source,Outlet_Years
0,FDW58,Low Fat,Snack Foods,OUT049,Medium,Tier 1,Supermarket Type1,test,14
1,FDW14,reg,Dairy,OUT017,NaN,Tier 2,Supermarket Type1,test,6
2,NCN55,Low Fat,Others,OUT010,NaN,Tier 3,Grocery Store,test,15
3,FDQ58,Low Fat,Snack Foods,OUT017,NaN,Tier 2,Supermarket Type1,test,6
4,FDY38,Regular,Dairy,OUT027,Medium,Tier 3,Supermarket Type3,test,28

In [109]:
new_data['Item_Fat_Content']=new_data['Item_Fat_Content'].map({'reg':'Regular','LF':'Low Fat','Low Fat':'Low Fat','Regular':'Regular'})

C:\Users\heman\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [110]:
#Outlet Years 
new_data.head()

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source,Outlet_Years
0,FDW58,Low Fat,Snack Foods,OUT049,Medium,Tier 1,Supermarket Type1,test,14
1,FDW14,Regular,Dairy,OUT017,NaN,Tier 2,Supermarket Type1,test,6
2,NCN55,Low Fat,Others,OUT010,NaN,Tier 3,Grocery Store,test,15
3,FDQ58,Low Fat,Snack Foods,OUT017,NaN,Tier 2,Supermarket Type1,test,6
4,FDY38,Regular,Dairy,OUT027,Medium,Tier 3,Supermarket Type3,test,28

In [111]:
new_data['Outlet_Years'].describe()

count    14204.000000
mean        15.169319
std          8.371664
min          4.000000
25%          9.000000
50%         14.000000
75%         26.000000
max         28.000000
Name: Outlet_Years, dtype: float64

In [112]:
new_data.Item_Fat_Content.unique()

array(['Low Fat', 'Regular', nan], dtype=object)

In [113]:
# frequency of variables
new_data["Item_Fat_Content"].value_counts()

Low Fat    9007
Regular    5019
Name: Item_Fat_Content, dtype: int64

In [114]:
from sklearn.preprocessing import LabelEncoder

In [115]:
le = LabelEncoder()
type(le)

sklearn.preprocessing.label.LabelEncoder

In [119]:
"""num_data=pd.DataFrame()
for i in new_data.columns:
    num_data[i] = le.fit_transform(new_data[i].astype(str))"""
var= ['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Outlet_Type',]
for i in var:
    new_data[i] = le.fit_transform(new_data[i].astype(str))

C:\Users\heman\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [120]:
new_data.head()

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Source,Outlet_Years
0,FDW58,0,Snack Foods,OUT049,1,0,1,test,14
1,FDW14,1,Dairy,OUT017,3,1,1,test,6
2,NCN55,0,Others,OUT010,3,2,0,test,15
3,FDQ58,0,Snack Foods,OUT017,3,1,1,test,6
4,FDY38,1,Dairy,OUT027,1,2,3,test,28

In [123]:
new_data = pd.get_dummies(new_data, columns=['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Outlet_Type'])

In [124]:
num_data.columns

Index(['Item_Identifier', 'Item_Type', 'Outlet_Identifier', 'Source',
       'Outlet_Years', 'Item_Fat_Content_0', 'Item_Fat_Content_1',
       'Item_Fat_Content_2', 'Outlet_Location_Type_0',
       'Outlet_Location_Type_1', 'Outlet_Location_Type_2', 'Outlet_Size_0',
       'Outlet_Size_1', 'Outlet_Size_2', 'Outlet_Size_3', 'Outlet_Type_0',
       'Outlet_Type_1', 'Outlet_Type_2', 'Outlet_Type_3'],
      dtype='object')

In [125]:
new_data.head()

,Item_Identifier,Item_Type,Outlet_Identifier,Source,Outlet_Years,Item_Fat_Content_0,Item_Fat_Content_1,Item_Fat_Content_2,Outlet_Location_Type_0,Outlet_Location_Type_1,Outlet_Location_Type_2,Outlet_Size_0,Outlet_Size_1,Outlet_Size_2,Outlet_Size_3,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2,Outlet_Type_3
0,FDW58,Snack Foods,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
1,FDW14,Dairy,OUT017,test,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
2,NCN55,Others,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
3,FDQ58,Snack Foods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
4,FDY38,Dairy,OUT027,test,28,0,1,0,0,0,1,0,1,0,0,0,0,0,1

In [126]:
data_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Source
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,train
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,train
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,train

In [69]:
num_data.head()

,Item_Identifier,Item_Type,Outlet_Identifier,Source,Outlet_Years,Item_Fat_Content_0,Item_Fat_Content_1,Item_Fat_Content_2,Outlet_Location_Type_0,Outlet_Location_Type_1,Outlet_Location_Type_2,Outlet_Size_0,Outlet_Size_1,Outlet_Size_2,Outlet_Size_3,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2,Outlet_Type_3
0,1114,13,9,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0
1,1078,4,2,0,7,0,1,0,0,1,0,0,0,0,1,0,1,0,0
2,1420,11,0,0,2,1,0,0,0,0,1,0,0,0,1,1,0,0,0
3,817,13,2,0,7,1,0,0,0,1,0,0,0,0,1,0,1,0,0
4,1197,4,5,0,5,0,1,0,0,0,1,0,1,0,0,0,0,0,1

In [129]:
new_data.rename(columns={'Item_Fat_Content_0':'Low Fat','Item_Fat_Content_1':'Regular','Item_Fat_Content_2':'nan'})

,Item_Identifier,Item_Type,Outlet_Identifier,Source,Outlet_Years,Low Fat,Regular,nan,Outlet_Location_Type_0,Outlet_Location_Type_1,Outlet_Location_Type_2,Outlet_Size_0,Outlet_Size_1,Outlet_Size_2,Outlet_Size_3,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2,Outlet_Type_3
0,FDW58,Snack Foods,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
1,FDW14,Dairy,OUT017,test,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
2,NCN55,Others,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
3,FDQ58,Snack Foods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
4,FDY38,Dairy,OUT027,test,28,0,1,0,0,0,1,0,1,0,0,0,0,0,1
5,FDH56,Fruits and Vegetables,OUT046,test,16,0,1,0,1,0,0,0,0,1,0,0,1,0,0
6,FDL48,Baking Goods,OUT018,test,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
7,FDC48,Baking Goods,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
8,FDN33,Snack Foods,OUT045,test,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0
9,FDA36,Baking Goods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
10,FDT44,Fruits and Vegetables,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
11,FDQ56,Fruits and Vegetables,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
12,NCC54,Health and Hygiene,OUT019,test,28,1,0,0,1,0,0,0,0,1,0,1,0,0,0
13,FDU11,Breads,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
14,DRL59,Hard Drinks,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
15,FDM24,Baking Goods,OUT049,test,14,0,1,0,1,0,0,0,1,0,0,0,1,0,0
16,FDI57,Seafood,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
17,DRC12,Soft Drinks,OUT018,test,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
18,NCM42,Household,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
19,FDA46,Snack Foods,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
20,FDA31,Fruits and Vegetables,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
21,NCJ31,Others,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
22,FDG52,Frozen Foods,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
23,NCL19,Others,OUT019,test,28,1,0,0,1,0,0,0,0,1,0,1,0,0,0
24,FDS10,Snack Foods,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
25,FDX22,Snack Foods,OUT010,test,15,0,1,0,0,0,1,0,0,0,1,1,0,0,0
26,NCF19,Household,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
27,NCE06,Household,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
28,DRC27,Dairy,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
29,FDE21,Fruits and Vegetables,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8493,FDP21,Snack Foods,OUT017,train,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8494,NCI54,Household,OUT017,train,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
8495,FDE22,Snack Foods,OUT035,train,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
8496,FDJ57,Seafood,OUT017,train,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8497,FDT08,Fruits and Vegetables,OUT035,train,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
8498,NCP54,Household,OUT018,train,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
8499,NCK53,Health and Hygiene,OUT035,train,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
8500,NCQ42,Household,OUT017,train,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
8501,FDW21,Snack Foods,OUT017,train,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8502,NCH43,Household,OUT045,train,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
8503,FDQ44,Fruits and Vegetables,OUT035,train,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
8504,NCN18,Household,OUT027,train,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
8505,FDB46,Snack Foods,OUT018,train,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
8506,DRF37,Soft Drinks,OUT018,train,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
8507,FDN28,Frozen Foods,OUT035,train,9,0,1,0,0,1,0,0,0,1,0,0,1,0,0
8508,FDW31,Fruits and Vegetables,OUT045,train,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8509,FDG45,Fruits and Vegetables,OUT010,train,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
8510,FDN58,Snack Foods,OUT035,train,9,0,1,0,0,1,0,0,0,1,0,0,1,0,0
8511,FDF05,Frozen Foods,OUT018,train,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
8512,FDR26,Dairy,OUT013,train,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
8513,FDH31,Meat,OUT035,train,9,0,1,0,0,1,0,0,0,1,0,0,1,0,0
8514,FDA01,Canned,OUT045,train,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8515,FDH24,Baking Goods,OUT018,train,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
8516,NCJ19,Others,OUT018,train,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
8517,FDF53,Frozen Foods,OUT046,train,16,0,1,0,1,0,0,0,0,1,0,0,1,0,0
8518,FDF22,Snack Foods,OUT013,train,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
8519,FDS36,Baking Goods,OUT045,train,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0
8520,NCJ29,Health and Hygiene,OUT035,train,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
8521,FDN46,Snack Foods,OUT018,train,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
8522,DRG01,Soft Drinks,OUT046,train,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0

In [130]:
# Exporting Data
data_train1 = new_data.loc[new_data['Source']=='train']
data_test1 = new_data.loc[new_data['Source']=='test']

In [132]:
data_train1.to_csv(r"C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Train_modified.csv")

In [133]:
data_test1.to_csv(r"C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Test_modified.csv")

In [134]:
data_testmodified = pd.read_csv(r"C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Test_modified.csv")
data_trainmodified = pd.read_csv(r"C:\Users\heman\OneDrive\Desktop\Datascience\Datasets\Sales\Train_modified.csv")

In [137]:
data_testmodified.drop('Unnamed: 0',axis=True)

,Item_Identifier,Item_Type,Outlet_Identifier,Source,Outlet_Years,Item_Fat_Content_0,Item_Fat_Content_1,Item_Fat_Content_2,Outlet_Location_Type_0,Outlet_Location_Type_1,Outlet_Location_Type_2,Outlet_Size_0,Outlet_Size_1,Outlet_Size_2,Outlet_Size_3,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2,Outlet_Type_3
0,FDW58,Snack Foods,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
1,FDW14,Dairy,OUT017,test,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
2,NCN55,Others,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
3,FDQ58,Snack Foods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
4,FDY38,Dairy,OUT027,test,28,0,1,0,0,0,1,0,1,0,0,0,0,0,1
5,FDH56,Fruits and Vegetables,OUT046,test,16,0,1,0,1,0,0,0,0,1,0,0,1,0,0
6,FDL48,Baking Goods,OUT018,test,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
7,FDC48,Baking Goods,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
8,FDN33,Snack Foods,OUT045,test,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0
9,FDA36,Baking Goods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
10,FDT44,Fruits and Vegetables,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
11,FDQ56,Fruits and Vegetables,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
12,NCC54,Health and Hygiene,OUT019,test,28,1,0,0,1,0,0,0,0,1,0,1,0,0,0
13,FDU11,Breads,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
14,DRL59,Hard Drinks,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
15,FDM24,Baking Goods,OUT049,test,14,0,1,0,1,0,0,0,1,0,0,0,1,0,0
16,FDI57,Seafood,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
17,DRC12,Soft Drinks,OUT018,test,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
18,NCM42,Household,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
19,FDA46,Snack Foods,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
20,FDA31,Fruits and Vegetables,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
21,NCJ31,Others,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
22,FDG52,Frozen Foods,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
23,NCL19,Others,OUT019,test,28,1,0,0,1,0,0,0,0,1,0,1,0,0,0
24,FDS10,Snack Foods,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
25,FDX22,Snack Foods,OUT010,test,15,0,1,0,0,0,1,0,0,0,1,1,0,0,0
26,NCF19,Household,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
27,NCE06,Household,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
28,DRC27,Dairy,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
29,FDE21,Fruits and Vegetables,OUT035,test,9,1,0,0,0,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5651,FDD23,Starchy Foods,OUT013,test,26,0,1,0,0,0,1,1,0,0,0,0,1,0,0
5652,FDP32,Fruits and Vegetables,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
5653,FDO31,Fruits and Vegetables,OUT035,test,9,0,1,0,0,1,0,0,0,1,0,0,1,0,0
5654,FDQ57,Snack Foods,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
5655,FDX32,Fruits and Vegetables,OUT027,test,28,0,1,0,0,0,1,0,1,0,0,0,0,0,1
5656,FDC39,Dairy,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
5657,FDU55,Fruits and Vegetables,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
5658,FDL45,Snack Foods,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
5659,DRK37,Soft Drinks,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
5660,FDK22,Snack Foods,OUT013,test,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0
5661,DRG37,Soft Drinks,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
5662,FDK22,Snack Foods,OUT017,test,6,1,0,0,0,1,0,0,0,0,1,0,1,0,0
5663,DRH36,Soft Drinks,OUT018,test,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
5664,DRC36,Soft Drinks,OUT018,test,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
5665,DRE03,Dairy,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
5666,FDF34,Snack Foods,OUT046,test,16,0,1,0,1,0,0,0,0,1,0,0,1,0,0
5667,FDZ22,Snack Foods,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
5668,FDC44,Fruits and Vegetables,OUT010,test,15,1,0,0,0,0,1,0,0,0,1,1,0,0,0
5669,FDN31,Fruits and Vegetables,OUT027,test,28,1,0,0,0,0,1,0,1,0,0,0,0,0,1
5670,FDO03,Meat,OUT017,test,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
5671,FDA01,Canned,OUT049,test,14,0,1,0,1,0,0,0,1,0,0,0,1,0,0
5672,NCH42,Household,OUT049,test,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
5673,FDF46,Snack Foods,OUT018,test,4,1,0,0,0,0,1,0,1,0,0,0,0,1,0
5674,DRL35,Hard Drinks,OUT046,test,16,1,0,0,1,0,0,0,0,1,0,0,1,0,0
5675,FDW46,Snack Foods,OUT049,test,14,0,1,0,1,0,0,0,1,0,0,0,1,0,0
5676,FDB58,Snack Foods,OUT046,test,16,0,1,0,1,0,0,0,0,1,0,0,1,0,0
5677,FDD47,Starchy Foods,OUT018,test,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
5678,NCO17,Health and Hygiene,OUT045,test,11,1,0,0,0,1,0,0,0,0,1,0,1,0,0
5679,FDJ26,Canned,OUT017,test,6,0,1,0,0,1,0,0,0,0,1,0,1,0,0
5680,FDU37,Canned,OUT045,test,11,0,1,0,0,1,0,0,0,0,1,0,1,0,0

In [138]:
data_trainmodified.drop()

,Unnamed: 0,Item_Identifier,Item_Type,Outlet_Identifier,Source,Outlet_Years,Item_Fat_Content_0,Item_Fat_Content_1,Item_Fat_Content_2,Outlet_Location_Type_0,Outlet_Location_Type_1,Outlet_Location_Type_2,Outlet_Size_0,Outlet_Size_1,Outlet_Size_2,Outlet_Size_3,Outlet_Type_0,Outlet_Type_1,Outlet_Type_2,Outlet_Type_3
0,0,FDA15,Dairy,OUT049,train,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
1,1,DRC01,Soft Drinks,OUT018,train,4,0,1,0,0,0,1,0,1,0,0,0,0,1,0
2,2,FDN15,Meat,OUT049,train,14,1,0,0,1,0,0,0,1,0,0,0,1,0,0
3,3,FDX07,Fruits and Vegetables,OUT010,train,15,0,1,0,0,0,1,0,0,0,1,1,0,0,0
4,4,NCD19,Household,OUT013,train,26,1,0,0,0,0,1,1,0,0,0,0,1,0,0